version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: fit-sharing-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fit-sharing-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: fit-sharing-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - mongo-data:/data/db

  fit-sharing-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongodb
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fit-sharing-db
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        SPRING_DATA_MONGODB_URI: mongodb://mongo:mongo@mongodb:27017/admin

volumes:
  postgres_data:
  mongo-data:

