-- liquibase formatted sql
-- changeset BorkowskiMaciej:1

CREATE SCHEMA IF NOT EXISTS app AUTHORIZATION postgres;

CREATE TABLE IF NOT EXISTS app.user (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

